### ISSUE TITLE
No mail sent, and apparently no error messages

### ISSUE THREAD

**Issue by Pio55** [ekutner/kopia-mon#10]
Hi,
I've installed you tool (thanks for sharing!), I need notifications after Kopia backups.
I'm facing an issue, I don't receive any email, and I don't understand what's wrong.
I'm the one who posted in Kopia forum, here:
[https://kopia.discourse.group/t/monitoring-and-alerting-tool-for-kopia/1697](url)

As you suggested there, I tried with the --no-send-email, but I didn't get any output in the shell:

![image](https://github.com/user-attachments/assets/1b7d3b59-a093-4858-a8a0-79f261ac5a4a)

Please let me know how I can help you to understand...
Many thanks,
Denis

**Comment by ekutner** [comment]
I suspect you have a YAML syntax error, which I see in the code just existed without giving proper notice.
Please run ```git pull``` and try again, it should give an error now if the problem is indeed a YAML syntax error.
If this is not the problem then please run the program with the -v parameter and attach your config file here as well.

**Comment by Pio55** [comment]
Hi,
thanks for your answer.
Actually, I don't know what `git pull` means...
Now I've downloaded "git" from here: [https://git-scm.com/downloads/win](url) (the portable version for Windows), and I've run:

![Immagine 2024-10-27 143015](https://github.com/user-attachments/assets/87a98c86-692c-4cd4-a201-d18cb60881f6)

It opens a CMD shell, but when I give the command `git pull`, it says some argument lacks, maybe  a path to kopia-mon files..:

![Immagine 2024-10-27 143136](https://github.com/user-attachments/assets/d37269ae-b7f5-4e11-9d7c-cb2684fc1717)

**Comment by ekutner** [comment]
I'm sorry for confusing you, I just assumed you were using git to clone the repository. Since you obviously didn't, then just ignore it, you don't need git and I assume you just downloaded the zip file from github. In that case just download it again and replace the old files.
