### ISSUE TITLE
[Request] making kopia-mon available via pypi?

### ISSUE THREAD

**Issue by FleischKarussel** [ekutner/kopia-mon#7]
Hey,

I just stumbled upon kopia-mon, because my backup was 3 weeks out of date. ;)
I'm not that proficient in using python venv's but I'm used to using pip install <name> to just install whatever comes around.

I don't have a clue how hard it is in the first place and how much work it is to maintain this, but would it be possible to make this brilliant tool available via pypi.org?
Maybe I can even can help with that?

Best regards
Benjamin

**Comment by ekutner** [comment]
Unfortunately I don't think it's possible to install this program through pypi because it needs to setup the directory structure with the HTML templates and config file and, as far as I know, that is not possible with a python package.  That said, using a venv is just a best practice, you don't have to use it if you're ok with installing all the dependencies to your main Python environment. Just follow the setup instructions and ignore the virtual environment.

**Comment by FleischKarussel** [comment]
Hey @ekutner and thanks for your response!

Well that's sad, I'd hoped it is comparable to something like rpm or deb packages with their feature set.
I'd like to keep the OS env as clean as possible, sure venv's seem to be clean as well, but some tedious hand work to get it running.
Anyway, would something like docker work in that regard?
I would figure that out myself and if you like, would MR this here, maybe someone else has use for that aswell.

Thanks

**Comment by ekutner** [comment]
docker can certainly work but it's a serious overkill for a small python program that runs once a day.
Setting up a venv is really very easy:
1. go the to program folder
2. create the venv using: ```python -m venv .venv```
3. activate the venv using ```.venv/bin/activate``` (assuming you're on linux)
4. Now you can install using pip and run python as usual, except it will be using the venv as the python environment

**Comment by FleischKarussel** [comment]
Yeah that might be the case, but i'd like to apply a standardized way of managing tools even just batch jobs like these.

I think I need to get used to venv and see how far I can get to make it that way. ;)

I had to use "source .venv/bin/activate" because activate is not executable by default

**Comment by ekutner** [comment]
ok, so it sounds like you figured out a way that works for you. any reason to keep this issue open?

**Comment by FleischKarussel** [comment]
Good morning,
Yes I did and this can be closed.
I'm currently working on the docker image and will open an MR when it's working. 😉

Thanks for your support!
